apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-team3-deployment
  namespace: team3ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5-team3
  template:
    metadata:
      labels:
        app: yolo5-team3
    spec:
      containers:
        - name: yolo5-container
          image: 933060838752.dkr.ecr.eu-central-1.amazonaws.com/yolo5-team3-ecr:22_20240207_084415
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
          envFrom:
          - secretRef:
              name: team3-yolo-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: yolo5-team3-service
  namespace: team3ns
spec:
  selector:
    app: yolo5-team3
  ports:
    - protocol: TCP
      port: 8081 # Match the port the container listens on
      targetPort: 8081 # Match the container port
  type: ClusterIP # ClusterIP for internal communication within the cluster
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5-hpa
  namespace: team3ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5-team3-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
