apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-team3-deployment
  namespace: team3ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5-team3
  template:
    metadata:
      labels:
        app: yolo5-team3
    spec:
      containers:
        - name: yolo5-container
          image: kinanhino/yolobot:1.0.4-amd64
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
          env:
            - name: BUCKET_NAME
              value: kin-docker-bucket
            - name: REGION
              value: us-east-1
            - name: SQS_QUEUE_NAME
              value: team3nsQueue
            - name: DYNAMO_TBL
              value: aws-dynamo-kinan
            - name: POLYBOT_URL
              value: 'http://team3polybot-service:8443'
---
apiVersion: v1
kind: Service
metadata:
  name: yolo5-team3-service
  namespace: team3ns
spec:
  selector:
    app: yolo5-team3
  ports:
    - protocol: TCP
      port: 8081 # Match the port the container listens on
      targetPort: 8081 # Match the container port
  type: ClusterIP # ClusterIP for internal communication within the cluster
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yolo5-hpa
  namespace: team3ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolo5-team3-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
